/* Generated By:JJTree: Do not edit this line. ASTDefinicionFuncion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTDefinicionFuncion extends SimpleNode {

    String nombre;

    public ASTDefinicionFuncion(int id) {
        super(id);
    }

    public ASTDefinicionFuncion(Parser p, int id) {
        super(p, id);
    }

    public void interpret() {
        Debug.println("<<Definicion funcion:" + nombre + ">>");

        // Almacenamos los nodos del proceso para su posterior interpretacion
        // Nodos.put(nombre, children);
        DefinicionProcedimientos.put(nombre, this);
    }
}
