/* Generated By:JJTree: Do not edit this line. ASTFunPri_MayorValor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_MayorValor extends SimpleNode {

    public ASTFunPri_MayorValor(int id) {
        super(id);
    }

    public ASTFunPri_MayorValor(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_MayorValor>>");
        
        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();
        int valor1 = ((DatoEntero) pila.pop()).getValor();

        jjtGetChild(1).interpret();
        int valor2 = ((DatoEntero) pila.pop()).getValor();

        int resultado = Math.max(valor1, valor2);

        // pila[++indicePila] = new DatoEntero(r.nextInt(value));
        pila.push(new DatoEntero(resultado));

    }

}
/* JavaCC - OriginalChecksum=0458b5adbf6572bbdb06ea9f0172a900 (do not edit this line) */
