/* Generated By:JJTree: Do not edit this line. ASTFunPri_Comienzacon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

import static edu.davinci.lenguaje.CustomNode.pila;
import edu.davinci.utils.Resource;
import java.text.MessageFormat;

public class ASTFunPri_Comienzacon extends SimpleNode {

    public ASTFunPri_Comienzacon(int id) {
        super(id);
    }

    public ASTFunPri_Comienzacon(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Comienzacon>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        // guardamos el texto
        String value = ((DatoTexto) pila.pop()).getValor();

        // Interpretamos la expresion de la funcion
        jjtGetChild(1).interpret();

        // guardamos
        String t1 = ((DatoTexto) pila.pop()).getValor();

        //verificamos
        boolean resultado = value.startsWith(t1);

        // almacenamos resultado
        pila.push(new DatoLogico(resultado));
    }

}
/* JavaCC - OriginalChecksum=6e93125d5f2831c568585c600c0895d9 (do not edit this line) */
