/* Generated By:JJTree: Do not edit this line. ASTFunPri_LetraAleatoria.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_LetraAleatoria extends SimpleNode {

    public ASTFunPri_LetraAleatoria(int id) {
        super(id);
    }

    public ASTFunPri_LetraAleatoria(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_LetraAleatoria>>");

        char r = (char) (Math.random() * 26 + 'a');
        String resultado = r + "";

        pila.push(new DatoTexto(resultado));

    }

}
/* JavaCC - OriginalChecksum=1ee82a97833c561153b7a0d658b931fc (do not edit this line) */
