/* Generated By:JJTree: Do not edit this line. ASTFunPri_Potencia.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Potencia extends SimpleNode {

    public ASTFunPri_Potencia(int id) {
        super(id);
    }

    public ASTFunPri_Potencia(Parser p, int id) {
        super(p, id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see edu.davinci.lenguaje.MyNode#interpret()
     */
    @Override
    public void interpret() {
        Debug.println("<<Pri_Potencia>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();
        int valor = ((DatoEntero) pila.pop()).getValor();

        jjtGetChild(1).interpret();
        int exponente = ((DatoEntero) pila.pop()).getValor();

        Double resultado = Math.pow(valor, exponente);
        
        // pila[++indicePila] = new DatoEntero(r.nextInt(value));
        pila.push(new DatoEntero(resultado.intValue()));

    }

}
/* JavaCC - OriginalChecksum=1f5b0cdca646dcc52702d5e5811cef19 (do not edit this line) */
