/* Generated By:JJTree: Do not edit this line. ASTFunPri_Logaritmo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Logaritmo extends SimpleNode {

    public ASTFunPri_Logaritmo(int id) {
        super(id);
    }

    public ASTFunPri_Logaritmo(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Logaritmo>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        int valor = ((DatoEntero) pila.pop()).getValor();

        Double resultado = Math.log(valor);

        pila.push(new DatoEntero(resultado.intValue()));

    }
}
/* JavaCC - OriginalChecksum=a5d8d26dc3852b1a169ddd5bc37d9aae (do not edit this line) */
