/* Generated By:JJTree: Do not edit this line. ASTFuncionUsuarioRetorno.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFuncionUsuarioRetorno extends SimpleNode {

    public ASTFuncionUsuarioRetorno(int id) {
        super(id);
    }

    public ASTFuncionUsuarioRetorno(Parser p, int id) {
        super(p, id);
    }

    /**
     *
     */
    public void interpret() {
        Debug.println("<<ASTValorFuncion - Interpretamos>>");

        //interpretamos la expresion del RETURN
        jjtGetChild(0).interpret();
    }
}
/* JavaCC - OriginalChecksum=35e823be2344738dbb83ea2eebee9ad1 (do not edit this line) */
