/* Generated By:JJTree: Do not edit this line. ASTFunPri_Terminacon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Terminacon extends SimpleNode {

    public ASTFunPri_Terminacon(int id) {
        super(id);
    }

    public ASTFunPri_Terminacon(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Terminacon>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        // guardamos el texto
        String value = ((DatoTexto) pila.pop()).getValor();

        // Interpretamos la expresion de la funcion
        jjtGetChild(1).interpret();

        // guardamos
        String t1 = ((DatoTexto) pila.pop()).getValor();

        //verificamos
        boolean resultado = value.endsWith(t1);

        // almacenamos resultado
        pila.push(new DatoLogico(resultado));
    }
}
/* JavaCC - OriginalChecksum=2143aba89b9bee7e98c567e292f3edce (do not edit this line) */
