/* Generated By:JJTree: Do not edit this line. ASTFunPri_Coseno.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Coseno extends SimpleNode {

    public ASTFunPri_Coseno(int id) {
        super(id);
    }

    public ASTFunPri_Coseno(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Coseno>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        int valor = ((DatoEntero) pila.pop()).getValor();

        Double resultado = Math.cos(valor);

        pila.push(new DatoEntero(resultado.intValue()));

    }

}
/* JavaCC - OriginalChecksum=247b1500e3b09b89a17ccdecd52c73b3 (do not edit this line) */
