/* Generated By:JJTree: Do not edit this line. ASTFunPri_Seno.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Seno extends SimpleNode {

    public ASTFunPri_Seno(int id) {
        super(id);
    }

    public ASTFunPri_Seno(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Seno>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        int valor = ((DatoEntero) pila.pop()).getValor();

        Double resultado = Math.sin(valor);
        
        pila.push(new DatoEntero(resultado.intValue()));

    }
}
/* JavaCC - OriginalChecksum=2e110dfab3c75c27947f0d7fce904157 (do not edit this line) */
