/* Generated By:JJTree: Do not edit this line. ASTFunPri_Cortar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Cortar extends SimpleNode {

    public ASTFunPri_Cortar(int id) {
        super(id);
    }

    public ASTFunPri_Cortar(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Cortar>>");

        // Interpretamos la expresion
        jjtGetChild(0).interpret();

        // guardamos el texto
        String value = ((DatoTexto) pila.pop()).getValor();

        String resultado = value.trim();

        pila.push(new DatoTexto(resultado));

    }

}
/* JavaCC - OriginalChecksum=b23b4ed6f4323df365bdddde1ba34637 (do not edit this line) */
