/* Generated By:JJTree: Do not edit this line. ASTFunPri_Tangente.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Tangente extends SimpleNode {

    public ASTFunPri_Tangente(int id) {
        super(id);
    }

    public ASTFunPri_Tangente(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Tangente>>");

        // Interpretamos la expresion de la funcion
        jjtGetChild(0).interpret();

        int valor = ((DatoEntero) pila.pop()).getValor();

        Double resultado = Math.tan(valor);

        pila.push(new DatoEntero(resultado.intValue()));

    }
}
/* JavaCC - OriginalChecksum=8269cb828aaed9823e61d5f975a55f1c (do not edit this line) */
