/* Generated By:JJTree: Do not edit this line. ASTFunPri_Mayuscula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Mayuscula extends SimpleNode {

    public ASTFunPri_Mayuscula(int id) {
        super(id);
    }

    public ASTFunPri_Mayuscula(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Mayuscula>>");

        // Interpretamos la expresion
        jjtGetChild(0).interpret();

        // guardamos el texto
        String value = ((DatoTexto) pila.pop()).getValor();

        String resultado = value.toUpperCase();

        pila.push(new DatoTexto(resultado));
        
    }

}
/* JavaCC - OriginalChecksum=a355319d48894daa52701395a50542aa (do not edit this line) */
