/* Generated By:JJTree: Do not edit this line. ASTFunPri_Minuscula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package edu.davinci.lenguaje;

public class ASTFunPri_Minuscula extends SimpleNode {

    public ASTFunPri_Minuscula(int id) {
        super(id);
    }

    public ASTFunPri_Minuscula(Parser p, int id) {
        super(p, id);
    }

    @Override
    public void interpret() {
        Debug.println("<<Pri_Minuscula>>");

        // Interpretamos la expresion
        jjtGetChild(0).interpret();

        // guardamos el texto
        String value = ((DatoTexto) pila.pop()).getValor();

        String resultado = value.toLowerCase();

        pila.push(new DatoTexto(resultado));

    }

}
/* JavaCC - OriginalChecksum=dbd0c2aac12b7e07ba29a029a6db9b79 (do not edit this line) */
