/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package edu.davinci.lenguaje;

public interface ParserTreeConstants
{
  public int JJTCOMPILAR = 0;
  public int JJTVOID = 1;
  public int JJTDEFINICIONHILO = 2;
  public int JJTPARAMETROSFORMALESHILO = 3;
  public int JJTPARAMETROFORMALENTRADAHILO = 4;
  public int JJTDEFINICIONPROCEDIMIENTO = 5;
  public int JJTDEFINICIONFUNCION = 6;
  public int JJTFUNCIONUSUARIORETORNO = 7;
  public int JJTPARAMETROSFORMALES = 8;
  public int JJTPARAMETROFORMALENTRADA = 9;
  public int JJTPARAMETROFORMALSALIDA = 10;
  public int JJTPARAMETROFORMALENTRADASALIDA = 11;
  public int JJTDEFINICIONVARIABLE = 12;
  public int JJTPRI_INICIAR = 13;
  public int JJTPRI_MOVER = 14;
  public int JJTPRI_DERECHA = 15;
  public int JJTPRI_TOMARFLOR = 16;
  public int JJTPRI_TOMARPAPEL = 17;
  public int JJTPRI_DEPOSITARFLOR = 18;
  public int JJTPRI_DEPOSITARPAPEL = 19;
  public int JJTASIGNACION = 20;
  public int JJTIDENTIFICADOR = 21;
  public int JJTFUNCIONUSUARIO = 22;
  public int JJTEXPRESION = 23;
  public int JJTOPERACIONREL = 24;
  public int JJTOPERACIONSUM = 25;
  public int JJTOPERACIONMUL = 26;
  public int JJTOPERACIONNEG = 27;
  public int JJTFUNPRI_ALEATORIO = 28;
  public int JJTFUNPRI_MINUSCULA = 29;
  public int JJTFUNPRI_MAYUSCULA = 30;
  public int JJTFUNPRI_CORTAR = 31;
  public int JJTFUNPRI_REEMPLAZAR = 32;
  public int JJTFUNPRI_COMIENZACON = 33;
  public int JJTFUNPRI_TERMINACON = 34;
  public int JJTFUNPRI_INDICEDE = 35;
  public int JJTFUNPRI_RAIZ = 36;
  public int JJTFUNPRI_POTENCIA = 37;
  public int JJTFUNPRI_MAYORVALOR = 38;
  public int JJTFUNPRI_SENO = 39;
  public int JJTFUNPRI_COSENO = 40;
  public int JJTFUNPRI_TANGENTE = 41;
  public int JJTFUNPRI_LOGARITMO = 42;
  public int JJTFUNPRI_LETRAALEATORIA = 43;
  public int JJTFUNPRI_LONGITUD = 44;
  public int JJTFUNPRI_SUSTRAER = 45;
  public int JJTFUNPRI_NUMEROATEXTO = 46;
  public int JJTFUNPRI_TEXTOANUMERO = 47;
  public int JJTFUNPRI_LOGICOATEXTO = 48;
  public int JJTFUNPRI_HAYROBOT = 49;
  public int JJTPRI_VARIABLE = 50;
  public int JJTOPERADORADITIVO = 51;
  public int JJTOPERADORMULTIPLICATIVO = 52;
  public int JJTOPERADORRELACIONAL = 53;
  public int JJTSIGNOTERMINO = 54;
  public int JJTCONSTANTEINT = 55;
  public int JJTCONSTANTESTR = 56;
  public int JJTCONSTANTEBOOLTRUE = 57;
  public int JJTCONSTANTEBOOLFALSE = 58;
  public int JJTSELECCION = 59;
  public int JJTBLOQUE = 60;
  public int JJTITERACIONCONDICIONAL = 61;
  public int JJTITERACIONINCONDICIONAL = 62;
  public int JJTPROCEDIMIENTOUSUARIO = 63;
  public int JJTPROCEDIMIENTOUSUARIOHILO = 64;
  public int JJTINFORMAR = 65;
  public int JJTLEER = 66;
  public int JJTPRI_POS = 67;
  public int JJTPRI_INICIARSEMAFORO = 68;
  public int JJTPRI_PS = 69;
  public int JJTPRI_PE = 70;


  public String[] jjtNodeName = {
    "Compilar",
    "void",
    "DefinicionHilo",
    "ParametrosFormalesHilo",
    "ParametroFormalEntradaHilo",
    "DefinicionProcedimiento",
    "DefinicionFuncion",
    "FuncionUsuarioRetorno",
    "ParametrosFormales",
    "ParametroFormalEntrada",
    "ParametroFormalSalida",
    "ParametroFormalEntradaSalida",
    "DefinicionVariable",
    "Pri_Iniciar",
    "Pri_Mover",
    "Pri_Derecha",
    "Pri_TomarFlor",
    "Pri_TomarPapel",
    "Pri_DepositarFlor",
    "Pri_DepositarPapel",
    "Asignacion",
    "Identificador",
    "FuncionUsuario",
    "Expresion",
    "OperacionRel",
    "OperacionSum",
    "OperacionMul",
    "OperacionNeg",
    "FunPri_Aleatorio",
    "FunPri_Minuscula",
    "FunPri_Mayuscula",
    "FunPri_Cortar",
    "FunPri_Reemplazar",
    "FunPri_Comienzacon",
    "FunPri_Terminacon",
    "FunPri_Indicede",
    "FunPri_Raiz",
    "FunPri_Potencia",
    "FunPri_MayorValor",
    "FunPri_Seno",
    "FunPri_Coseno",
    "FunPri_Tangente",
    "FunPri_Logaritmo",
    "FunPri_LetraAleatoria",
    "FunPri_Longitud",
    "FunPri_Sustraer",
    "FunPri_NumeroATexto",
    "FunPri_TextoANumero",
    "FunPri_LogicoATexto",
    "FunPri_HayRobot",
    "Pri_Variable",
    "OperadorAditivo",
    "OperadorMultiplicativo",
    "OperadorRelacional",
    "SignoTermino",
    "ConstanteInt",
    "ConstanteStr",
    "ConstanteBoolTrue",
    "ConstanteBoolFalse",
    "Seleccion",
    "Bloque",
    "IteracionCondicional",
    "IteracionIncondicional",
    "ProcedimientoUsuario",
    "ProcedimientoUsuarioHilo",
    "Informar",
    "Leer",
    "Pri_Pos",
    "Pri_IniciarSemaforo",
    "Pri_PS",
    "Pri_PE",
  };
}
/* JavaCC - OriginalChecksum=39ab7dbc5c974288d729babe980b4d00 (do not edit this line) */
